# Generated by Django 3.0.2 on 2020-01-09 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('color_seasons', '0002_auto_20200108_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='seasons', to='color_seasons.Color'),
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('picture', models.URLField()),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosts', to='color_seasons.Season')),
            ],
        ),
    ]
