# Generated by Django 3.0.2 on 2020-01-09 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('color_seasons', '0003_auto_20200109_0554'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Color',
            new_name='Category',
        ),
        migrations.RemoveField(
            model_name='hexcolor',
            name='color',
        ),
        migrations.AddField(
            model_name='hexcolor',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='color_seasons.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hexcolor',
            name='name',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='season',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='seasons', to='color_seasons.HexColor'),
        ),
    ]
