# Generated by Django 3.0.2 on 2020-04-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color_seasons', '0004_auto_20200109_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='happy_picture',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
